[sncast.default]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"

[sncast.sepolia]
account = "deployer"
accounts-file = "/root/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
